// Generated by CoffeeScript 1.6.3
var pkg;

pkg = require('../package.json');

module.exports = require('rc')(pkg.name, {
  endpoint: null,
  aws_access_key: null,
  aws_access_key_id: null,
  aws_region: null
});
