// Generated by CoffeeScript 1.6.3
var aws, config, glacierSettings;

aws = require('aws-sdk');

config = require('./config');

aws.config.update({
  accessKeyId: config.aws_access_key_id,
  secretAccessKey: config.aws_access_key,
  region: config.aws_region
});

glacierSettings = {
  apiVersion: '2012-06-01'
};

if (config.endpoint) {
  glacierSettings.endpoint = config.endpoint;
}

module.exports = new aws.Glacier(glacierSettings);
